version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql
    ports:
      - "3306:3306"
    networks:
      - medical-net
    healthcheck: # <-- ¡Añade o verifica esta sección!
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s # Dale tiempo a MySQL para arrancar completamente
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=reservationsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts/init-reservations.sql:/docker-entrypoint-initdb.d/init-reservations.sql
    ports:
      - "5432:5432"
    networks:
      - medical-net
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - medical-net
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - medical-net
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    networks:
      - medical-net
  grafana:
    image: grafana/grafana:9.5.0
    ports:
      - "3000:3000"
    networks:
      - medical-net
    depends_on:
      - loki
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - MYSQL_HOST=mysql
      - JWT_SECRET=your_secret
    networks:
      - medical-net
    depends_on:
      - mysql
      - loki
  specialties-service:
    build: ./specialties-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/specialtiesdb
      - JWT_SECRET=your_secret
    networks:
      - medical-net
    depends_on:
      - mongo
      - loki
  reservations-service:
    build: ./reservations-service
    ports:
      - "3003:3003"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=reservationsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - RABBITMQ_HOST=rabbitmq
      - JWT_SECRET=your_secret
      - AUTH_SERVICE_URL=http://auth-service:3001
    networks:
      - medical-net
    depends_on:
      - postgres
      - rabbitmq
      - loki
  notifications-service:
    build: ./notifications-service
    ports:
      - "3004:3004"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - NOTIFICATION_API_URL=http://example.com/send
    networks:
      - medical-net
    depends_on:
      - rabbitmq
      - loki
  nginx:
    build: ./nginx # El Dockerfile de Nginx seguirá en ./nginx
    ports:
      - "80:80" # Nginx escuchará en el puerto 80 del host
    depends_on:
      - frontend # <-- Nginx ahora depende del frontend
      - auth-service
      - specialties-service
      - reservations-service
    networks:
      - medical-net
  frontend:
    build:
      context: ./frontend # El contexto de construcción es tu carpeta 'frontend'
      dockerfile: Dockerfile # Busca el Dockerfile directamente en 'frontend/'
    container_name: frontend # Nombre del contenedor
    ports:
      - "3005:3005" # Mapea el puerto 3000 del host al 3000 del contenedor (donde http-server escucha)
    networks:
      - medical-net

volumes:
  mysql-data:
  postgres-data:
  mongo-data:
networks:
  medical-net:
    driver: bridge