version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always
    environment:
      HOST: db   # Importante: usa el nombre del servicio 'db'
      USER: root
      PASSWORD: password
      DATABASE: usuariosdb

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usuariosdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: