CREATE DATABASE IF NOT EXISTS authdb;
USE authdb;
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('paciente', 'medico', 'admin') NOT NULL,
  name VARCHAR(255) NOT NULL
);